Add new opttion engine-strict
ioBroker/testing-action-adapter pull request #11
Opened 2024-11-21 17:44 UTC by mcm1957

This PR adapts testing-action-adapter as following:

If new option engine-strict is not set to false (the default is true) 'npm set config engine-strict=true' is executed before executing the npm installation command (default 'npm ci'). So unless the dev sets option egine-strcit to false the npm installation checks the requirements of all packages installed (including complete dependen packages) and fails if one of those packages is incompatible with the node.js release runnoing the test.

Existing workflows need not be modifed unless there is a good reason to disable this check.

2024-11-21 17:46 UTC, mcm1957 commented
fixes https://github.com/ioBroker/testing-action-adapter/issues/8

2024-11-22 14:49 UTC, AlCalzone requested changes
Just a small nit. The new option should also be mentioned in the table in the README.

2024-11-22 14:49 UTC, AlCalzone commented on action.yml
> +    - name: Prepare npm
```suggestion
    - name: Configure npm

```

2024-11-22 15:39 UTC, AlCalzone approved these changes

2024-11-22 15:40 UTC, AlCalzone commented
Thanks! Will merge and release later.

2024-11-22 16:53 UTC, mcm1957 commented
Fell free to do whenever you have time to check functionality

2024-11-22 18:25 UTC, merged